* Updated the version of the PDF library and included BouncyCastle to get rid of the following exceptions: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/ASN1OctetString         at com.itextpdf.text.pdf.PdfEncryption.<init>(PdfEncryption.java:147)         at com.itextpdf.text.pdf.PdfReader.readDecryptedDocObj(PdfReader.java:776)         at com.itextpdf.text.pdf.PdfReader.readDocObj(PdfReader.java:1153)         at com.itextpdf.text.pdf.PdfReader.readPdf(PdfReader.java:509)         at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:188)         at com.itextpdf.text.pdf.PdfReader.<init>(PdfReader.java:177)         at com.zuehlke.pgadmissions.pdf.PdfDocumentBuilder.readPdf(PdfDocumentBuilder.java:1011)         at com.zuehlke.pgadmissions.pdf.PdfDocumentBuilder.addSupportingDocuments(PdfDocumentBuilder.java:961)         at com.zuehlke.pgadmissions.pdf.PdfDocumentBuilder.buildDocument(PdfDocumentBuilder.java:190)         at com.zuehlke.pgadmissions.pdf.PdfDocumentBuilder.buildDocument(PdfDocumentBuilder.java:131)         at com.zuehlke.pgadmissions.pdf.PdfDocumentBuilder.buildPdfWithAttachments(PdfDocumentBuilder.java:117)         at com.zuehlke.pgadmissions.mail.RegistryMailSender.sendApplicationToRegistryContacts(RegistryMailSender.java:60)         at com.zuehlke.pgadmissions.timers.RegistryNotificationTimerTask.run(RegistryNotificationTimerTask.java:56)         at java.util.TimerThread.mainLoop(Timer.java:534)         at java.util.TimerThread.run(Timer.java:484) Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.ASN1OctetString